### ISSUE TITLE
Joining JuliaGaming

### ISSUE THREAD

**Issue by logankilpatrick** [mossr/Tetris.jl#1]
Hey Robert, I just sent you an owner invite for the Julia Gaming Org, if you have an interest in joining, it would be cool to consolidate these games into a single org so if you want to join and move this repo over, feel free too. No worries either way, this is a cool very project!

**Comment by mossr** [comment]
Awesome—thank you! I have a non-one-liner version of this code that may be more suited for JuliaGaming (and not the [`TetrisExpanded.jl`](https://github.com/mossr/Tetris.jl/blob/master/src/TetrisExpanded.jl) version but an actual non-obfuscated version). I'll most likely rename this repo to `Tetris1.jl` and create `Tetris.jl` under JuliaGaming.

**Comment by logankilpatrick** [comment]
Wonderful! Glad to hear it and great work again.

**Comment by mossr** [comment]
@logankilpatrick I pushed my un-obfuscated version to JuliaGaming: https://github.com/JuliaGaming/Tetris

That version is much cleaner for the JuliaGaming community to use: [tetris.jl](https://github.com/JuliaGaming/Tetris/blob/master/Tetris-mossr/tetris.jl)

**Comment by logankilpatrick** [comment]
Awesome! Thank you.
